/*
'use client'
import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
*/



import Link from 'next/link';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between bg-gradient-to-r from-purple-500 to-blue-500">
      <div className='flex flex-row justify-between mt-5 px-5 w-full text-white text-xl '>
        HomePage
        <Link href="/login" className='mr-5' >Login Here</Link>
      </div>
    </main>
  );
}
